apiVersion: v1
kind: Service
metadata: 
  name: angular-service
  labels:
    app: traffic-app
    tier: front-end
spec:
  type: ClusterIP
  selector:
    app: traffic-app
    tier: front-end
  ports:
    - protocol: TCP
      port: 80
      name: http