apiVersion: apps/v1
kind: Deployment 
metadata:
  name: traffic-app-deployment
  labels:
    app: traffic-app
spec:
  replicas: 2  
  selector: 
    matchLabels:
      app: traffic-app
  template: 
    metadata:
      name: traffic-app-pod
      labels:
        app: traffic-app
    spec:
      containers:
        - name: hello-world-container
          image: wouterm/helloworld